#########################
### build environment ###
#########################

# base image
FROM node:14.17.0 as development

# # install chrome for protractor tests
# RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
# RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
# RUN apt-get update && apt-get install -yq google-chrome-stable

# set working directory
RUN mkdir /usr/src/app
WORKDIR /usr/src/app

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

EXPOSE 4200

# install and cache app dependencies
COPY package.json /usr/src/app/package.json

RUN npm install
RUN npm install -g @angular/cli@1.7.3 --unsafe

# add app
COPY . /usr/src/app

RUN chmod 777 /usr/src/app/package*.json
COPY docker-entrypoint.sh /usr/src/app/docker-entrypoint.sh
RUN ls -al
ADD docker-entrypoint.sh /
RUN chmod 755 /docker-entrypoint.sh
CMD ["/docker-entrypoint.sh"]

##################
### production ###
##################

# base image
# FROM nginx:1.21.4-alpine as production

# # copy artifact build from the 'build environment'
# COPY --from=builder /usr/src/app/dist /usr/share/nginx/html

# # expose port 80
# EXPOSE 80

# # run nginx
# CMD ["nginx", "-g", "daemon off;"]
