FROM cypress/included:8.3.0

RUN mkdir /usr/src/app
WORKDIR /usr/src/app

COPY ./package*.json .

RUN npm install

COPY cypress.json /usr/src/app/cypress.json
COPY cypress /usr/src/app/cypress

RUN ./node_modules/.bin/cypress verify

ENTRYPOINT ["npm", "run"]