# This contains the browsers needed for Cypress

# base image
FROM cypress/browsers:node14.17.0-chrome91-ff89

# set working directory
RUN mkdir /usr/src/app
WORKDIR /usr/src/app

# install cypress
RUN npm install cypress@8.3.0

# copy cypress files and folders
COPY cypress /usr/src/app/cypress
COPY cypress-browsers.json /usr/src/app/cypress.json

# confirm the cypress install
RUN ./node_modules/.bin/cypress verify
